mode: cluster
dependencies:
  etcd:
    inCluster:
      values:
        replicaCount: 3
        resources:
            requests:
              cpu: 2
              memory: 3Gi
            limits:
              cpu: 8
              memory: 3Gi
  storage:
    inCluster:
      values:
        statefulset:
          replicaCount: 4
        resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 8
              memory: 16Gi
  pulsar:
    inCluster:
      values:
        components:
          autorecovery: false
          functions: false
          toolset: false
          pulsar_manager: false
        monitoring:
          prometheus: false
          grafana: false
          node_exporter: false
          alert_manager: false
        proxy:
          replicaCount: 1
          resources:
            requests:
              cpu: 2
              memory: 4096Mi
            limits:
              cpu: 6
              memory: 8192Mi
          configData:
            PULSAR_MEM: >
              -Xms4096m -Xmx4096m
            PULSAR_GC: >
              -XX:MaxDirectMemorySize=4096m
            httpNumThreads: "50"
        bookkeeper:
          replicaCount: 3
          resources:
            requests:
              cpu: 2
              memory: 8192Mi
            limits:
              cpu: 6
              memory: 24576Mi
          configData:
            PULSAR_MEM: >
              -Xms8192m
              -Xmx8192m
              -XX:MaxDirectMemorySize=16384m
            PULSAR_GC: >
              -Dio.netty.leakDetectionLevel=disabled
              -Dio.netty.recycler.linkCapacity=1024
              -XX:+UseG1GC -XX:MaxGCPauseMillis=10
              -XX:+ParallelRefProcEnabled
              -XX:+UnlockExperimentalVMOptions
              -XX:+DoEscapeAnalysis
              -XX:ParallelGCThreads=32
              -XX:ConcGCThreads=32
              -XX:G1NewSizePercent=50
              -XX:+DisableExplicitGC
              -XX:-ResizePLAB
              -XX:+ExitOnOutOfMemoryError
              -XX:+PerfDisableSharedMem
              -XX:+PrintGCDetails
        zookeeper:
          replicaCount: 3
          resources:
            requests:
              cpu: 0.6
              memory: 2048Mi
            limits:
              cpu: 2
              memory: 4096Mi
          configData:
            PULSAR_MEM: >
              -Xms2048m
              -Xmx2048m
            PULSAR_GC: >
              -Dcom.sun.management.jmxremote
              -Djute.maxbuffer=10485760
              -XX:+ParallelRefProcEnabled
              -XX:+UnlockExperimentalVMOptions
              -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC
              -XX:+PerfDisableSharedMem
              -Dzookeeper.forceSync=no
        broker:
          replicaCount: 1
          resources:
            requests:
              cpu: 3
              memory: 8192Mi
            limits:
              cpu: 6
              memory: 24576Mi
          configData:
            PULSAR_MEM: >
              -Xms8192m
              -Xmx8192m
            PULSAR_GC: >
              -XX:MaxDirectMemorySize=16384m
              -Dio.netty.leakDetectionLevel=disabled
              -Dio.netty.recycler.linkCapacity=1024
              -XX:+ParallelRefProcEnabled
              -XX:+UnlockExperimentalVMOptions
              -XX:+DoEscapeAnalysis
              -XX:ParallelGCThreads=32
              -XX:ConcGCThreads=32
              -XX:G1NewSizePercent=50
              -XX:+DisableExplicitGC
              -XX:-ResizePLAB
              -XX:+ExitOnOutOfMemoryError
components: 
  image: milvusdb/milvus:v2.1.0
  # mixCoord deploys all coordinators in one 'mixture' deployment
  mixCoord:
    replicas: 1
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 6Gi
  proxy:
    replicas: 2
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 4
        memory: 6Gi
  indexNode:
    replicas: 1
    resources:
      requests:
        cpu: 8
        memory: 8Gi
      limits:
        cpu: 12
        memory: 8Gi
  dataNode:
    replicas: 1
    resources:
      requests:
        cpu: 4
        memory: 8Gi
      limits:
        cpu: 8
        memory: 12Gi
  queryNode:
    replicas: 2
    resources:
      requests:
        cpu: 4
        memory: 40Gi
      limits:
        cpu: 10
        memory: 64Gi
config:
  milvus:
    log:
      level: info